mutation ($path: String!) {
  assets {
    createFoldersRecursively(path: $path) {
      responseResult {
        succeeded
        errorCode
        slug
        message,
      },
      folderId,
      folderPath
    }
  }
}
